version: '3.8'

services:

  api01: &api
    image: brunocsmaciel/rinha-backend-2024:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=mysql-rinha
    ports:
      - "8081:8080"
    depends_on:
      mysql-rinha:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "35MB"

  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_HOSTNAME=mysql-rinha
    ports:
      - "8082:8080"
 
  mysql-rinha:
    image: mysql:latest
    container_name: mysql-rinha
    environment:
      MYSQL_ROOT_PASSWORD: secretpass
      MYSQL_DATABASE: rinhabackend
      MYSQL_USER: rinha
      MYSQL_PASSWORD: secretpass
    healthcheck:
      test: "mysql -uroot -psecretpass -e 'select 1;'"
      interval: 3s
      retries: 20
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file=/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "440MB"

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"
    